config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items
  get "items/:id/viewer", to: "viewer#show", as: "item_viewer"


  root to: redirect('/items')

  # api_version(:module => "v0.1.0", :header => {:name => "Accept", :value => "application/iiif.nara.gove; version=1"}) do
  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => :json}) do
    resources :manifests
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :naId, presence: true

  default_scope {
    includes(:record_objects)
  }

  has_many :record_objects, as: :record_objectable, dependent: :destroy
  accepts_nested_attributes_for :record_objects, reject_if: :all_blank, allow_destroy: true  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(
        :title, 
        :naId, 
        record_objects_attributes: [
          :label, 
          :naId,
          :id,
          :_destroy,
          image_attributes: [
            :title, 
            :description, 
            :image, 
            :id, 
            :image_id,
            :_destroy
          ]
        ], 
      )
    end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, multipart: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mdc-text-field">
    <%= form.label :title, class: "mdc-floating-label" %>
    <%= form.text_field :title, class: "mdc-text-field__input" %>
  </div>
  <br>

  <div class="field mdc-text-field">
    <%= form.label :naId, class: "mdc-floating-label" %>
    <%= form.text_field :naId, class: "mdc-text-field__input" %>
  </div>

  <%# <%= render "shared/image_fields", form: form %>

  <div id='tasks'>
    <%= form.fields_for :record_objects do |record_group| %>
      <%= render 'record_object_fields', :f => record_group %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association '+ add record object', form, :record_objects, class: "mdc-button mdc-button--outlined" %>
    </div>
  </div>

  <div class="actions">
    <br>
    <%= form.submit 'Create Item', class:"mdc-button mdc-button--unelevated" %>
  </div>

<% end %>

app/views/items/_record_object_fields.erb
  <div class='nested-fields'>
    <h2>Record Object</h2>
    <div class="field mdc-text-field">
      <%= f.label :label, class: "mdc-floating-label" %>
      <%= f.text_field :label, class: "mdc-text-field__input" %>
    </div>
    <br>
    <div class="field mdc-text-field">
      <%= f.label :naId, class: "mdc-floating-label" %>
      <%= f.text_field :naId, class: "mdc-text-field__input" %>
    </div>

    <%= f.fields_for :image, f.object.image || Image.new do |image_fields| %>
      <fieldset>
        <legend>Image</legend>
        <div class="field">
          <%= image_fields.label :image, "Image File" %>
          <%= image_fields.file_field :image unless f.object.image.present? %>
          <% if f.object.try(:image).try(:present?) %>
            <p>
              <%= image_tag image_variant_url(f.object.image, :small), alt: '' %>
            </p>
          <% end %>
        </div>

        <div class="field mdc-text-field">
          <%= image_fields.label :title, "Image Title", class: "mdc-floating-label" %>
          <%= image_fields.text_field :title, class: "mdc-text-field__input" %>
        </div>
        <br>

        <div class="field mdc-text-field mdc-text-field--textarea">
          <%= image_fields.text_area :description, class: "mdc-text-field__input", rows: "3", cols: "100" %>
          <div class="mdc-notched-outline">
            <div class="mdc-notched-outline__leading"></div>

            <div class="mdc-notched-outline__notch">
              <%= image_fields.label :description, "Image Description", class: "mdc-floating-label" %>
            </div>
            <div class="mdc-notched-outline__trailing"></div>
          </div>
        </div>
        
      </fieldset>
    <% end %>

    <%= link_to_remove_association "remove record object", f, class: "mdc-button mdc-button--outlined" %>
  </div>

app/views/items/_record_object_grid.html.erb
<div class="mdc-layout-grid" style="max-width: 1000px; margin: 0 auto;">
  <div class="mdc-layout-grid__inner">
    <% @item.record_objects.each_with_index do |ro| %>
    <div class="mdc-layout-grid__cell">
      <div class="mdc-card demo-card">
        <div class="mdc-card__primary-action demo-card__primary-action" tabindex="0">
          <div class="mdc-card__media mdc-card__media--16-9 demo-card__media" style="background-image: url(<%= iiif_url_from_params(ro.image, {size: "300,300"}) %>);"></div>
          <div class="demo-card__primary">
            <h2 class="demo-card__title mdc-typography mdc-typography--headline6"><%= ro.label %></h2>
            <%# <h3 class="demo-card__subtitle mdc-typography mdc-typography--subtitle2">by Kurt Wagner</h3> %>
          </div>
          <div class="demo-card__secondary mdc-typography mdc-typography--body2">
          <%= link_to iiif_id_url(ro.image), iiif_id_url(ro.image), target: "_blank" %>
          </div>
        </div>
        <div class="mdc-card__actions">
          <div class="mdc-card__action-buttons">
            <button class="mdc-button mdc-card__action mdc-card__action--button">Read</button>
            <button class="mdc-button mdc-card__action mdc-card__action--button">Bookmark</button>
          </div>
          <div class="mdc-card__action-icons">
            <button class="mdc-icon-button mdc-card__action mdc-card__action--icon--unbounded" aria-pressed="false" aria-label="Add to favorites" title="Add to favorites">
              <i class="material-icons mdc-icon-button__icon mdc-icon-button__icon--on">favorite</i>
              <i class="material-icons mdc-icon-button__icon">favorite_border</i>
            </button>
            <button class="mdc-icon-button material-icons mdc-card__action mdc-card__action--icon--unbounded" title="Share" data-mdc-ripple-is-unbounded="true">share</button>
            <button class="mdc-icon-button material-icons mdc-card__action mdc-card__action--icon--unbounded" title="More options" data-mdc-ripple-is-unbounded="true">more_vert</button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mdc-typography--headline1">Items</h1>

<div class="mdc-data-table">
  <table class="mdc-data-table__table" aria-label="Dessert calories">
    <thead>
      <tr class="mdc-data-table__header-row">
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">Title</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">naId</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">Preview</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col" colspan="3"></th>
      </tr>
    </thead>
    <tbody class="mdc-data-table__content">
      <% @items.each do |item| %>
      <tr class="mdc-data-table__row">
        <td class="mdc-data-table__cell table__cell--title">
          <%= item.title %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <%= item.naId %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <% if item.record_objects.any? %>
            <% item.record_objects.each do |ro| %>
            <ul class="mdc-image-list my-image-list">
              <li class="mdc-image-list__item">
                <div class="mdc-image-list__image-aspect-container">
                  <%= image_tag iiif_url_from_params(ro.image, {size: "25,25"}), alt: '', class:"mdc-image-list__image" %>
                </div>
                <%# <div class="mdc-image-list__supporting">
                  <span class="mdc-image-list__label">Text label</span>
                </div> %>
              </li>
            </ul>
            <% end %>
          <% end %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <%= link_to 'Show', item, class: "mdc-button mdc-button--unelevated" %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <%= link_to 'Edit', edit_item_path(item), class: "mdc-button mdc-button--outlined" %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "mdc-button" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="tools-footer">
  <%= link_to 'New Item', new_item_path, class: "mdc-button mdc-button--unelevated" %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mdc-typography--headline3"><%= @item.title %></h1>

<p>
  <strong>NaId:</strong>
  <%= @item.naId %>
</p>

<p>
  <strong>Manifest:</strong>
  <%= link_to v1_manifest_url(@item.naId), v1_manifest_url(@item.naId), target: "_blank" %>
</p>

<p>
  <strong>Mirador Viewer (Local):</strong>
  <%= link_to item_viewer_url(@item), item_viewer_url(@item), target: "_blank" %>
</p>
<p>
  <strong>Universal Viewer (External):</strong>
  <%= link_to "http://universalviewer.io/uv.html?manifest=#{v1_manifest_url(@item.naId)}", "http://universalviewer.io/uv.html?manifest=#{v1_manifest_url(@item.naId)}", target: "_blank" %>
</p>

<h2 class="mdc-typography--headline5">Objects</h2>
<div class="mdc-data-table">
  <table class="mdc-data-table__table" aria-label="Dessert calories">
    <thead>
      <tr class="mdc-data-table__header-row">
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">Label</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">Thumbnail</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">Format</th>
        <th class="mdc-data-table__header-cell" role="columnheader" scope="col">IIIF @id</th>
      </tr>
    </thead>
    <tbody class="mdc-data-table__content">
      <% @item.record_objects.each_with_index do |ro| %>
      <tr class="mdc-data-table__row">
        <td class="mdc-data-table__cell table__cell--title">
          <%= ro.label %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric">
          <%= image_tag iiif_url_from_params(ro.image, {size: "75,75"}), alt: '' %>
        </td>
        <td>
          <%= ro.image.image.content_type %>
        </td>
        <td class="mdc-data-table__cell mdc-data-table__cell--numeric table__cell--id">
          <%= link_to iiif_id_url(ro.image), iiif_id_url(ro.image), target: "_blank" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%#= render "items/record_object_grid" %>

<div class="tools-footer">
  <%= link_to 'Edit', edit_item_path(@item), class: "mdc-button mdc-button--unelevated" %>
  <%= link_to 'Back', items_path, class: "mdc-button mdc-button--outlined" %>
</div>